import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { analyze, RULESET_VERSION } from '../server/rules.js';
import { demoSnapshot } from '../server/demo.js';
const cases = JSON.parse(
  readFileSync(new URL('../fixtures/evaluation.json', import.meta.url), 'utf8'),
);
const rows = cases.map((item) => {
  const snapshot = demoSnapshot('after');
  if (item.scripts)
    snapshot.files.find((f) => f.path === 'package.json').text = JSON.stringify({
      name: 'evaluation-fixture',
      scripts: item.scripts,
    });
  if (item.workflow) snapshot.files.find((f) => f.path.endsWith('.yml')).text = item.workflow;
  if (item.incomplete) snapshot.inventoryComplete = false;
  if (item.noWorkflows) {
    snapshot.files = snapshot.files.filter((f) => !f.path.endsWith('.yml'));
    snapshot.inventory = snapshot.inventory.filter((p) => !p.endsWith('.yml'));
  }
  const actual = analyze(snapshot).find((r) => r.ruleId === item.rule).outcome;
  return { ...item, actual, agrees: actual === item.expected };
});
const summaries = ['INSTALL-01', 'TEST-01', 'CI-01'].map((rule) => {
  const supported = rows.filter((r) => r.rule === rule && !r.outsideScope);
  return {
    rule,
    cases: supported.length,
    expectedMatches: supported.filter((r) => r.expected === 'match').length,
    falsePositives: supported.filter((r) => r.actual === 'match' && r.expected === 'no_match')
      .length,
    missedFindings: supported.filter((r) => r.expected === 'match' && r.actual !== 'match').length,
    inconclusive: supported.filter((r) => r.actual === 'inconclusive').length,
    disagreements: supported.filter((r) => !r.agrees).length,
  };
});
const text = [
  '# Rule evaluation',
  '',
  'Generated by `npm run evaluate` for rule set ' + RULESET_VERSION + '.',
  '',
  'This is a small, independently labeled synthetic contract corpus. It is not a random sample of GitHub repositories. It was added after the first unit-test suite but is not a blinded external benchmark; some conditions overlap development fixtures. Do not generalize these counts into real-world accuracy.',
  '',
  '| Rule | In-scope cases | Expected matches | False positives | Missed findings | Inconclusive | Contract disagreements |',
  '| --- | ---: | ---: | ---: | ---: | ---: | ---: |',
  ...summaries.map(
    (s) =>
      '| ' +
      [
        s.rule,
        s.cases,
        s.expectedMatches,
        s.falsePositives,
        s.missedFindings,
        s.inconclusive,
        s.disagreements,
      ].join(' | ') +
      ' |',
  ),
  '',
  'A false positive here means a match on an expected non-match. An expected match returned as inconclusive is counted as missed as well as inconclusive. All other outcome disagreements are listed explicitly. Expected-behavior reviewer decisions do not automatically count as detector false positives.',
  '',
  '| Case | Condition | Expected | Actual | Scope |',
  '| --- | --- | --- | --- | --- |',
  ...rows.map(
    (r) =>
      '| ' +
      [
        r.id,
        r.label,
        r.expected,
        r.actual,
        r.outsideScope ? 'Known limitation' : 'Supported contract',
      ].join(' | ') +
      ' |',
  ),
  '',
  '## Known limitations demonstrated',
  '',
  ...rows.filter((r) => r.outsideScope).map((r) => '- ' + r.id + ': ' + r.reason),
  '',
  'The quoted-URL pipeline demonstrates a broader pattern the first rule misses. It is excluded from the supported-syntax false-negative count, not hidden as evidence of complete detection. CI script delegation is explicitly inconclusive.',
  '',
  '## Next evaluation work',
  '',
  'Add independently reviewed real-repository samples and reserve a new holdout corpus before changing the rules. Record repository commits, adjudication reasons, ambiguous cases, and changes in supported scope.',
  '',
];
mkdirSync('docs', { recursive: true });
writeFileSync('docs/EVALUATION.md', text.join('\n'));
console.log(
  JSON.stringify(
    {
      ruleset: RULESET_VERSION,
      cases: rows.length,
      agreements: rows.filter((r) => r.agrees).length,
      summaries,
    },
    null,
    2,
  ),
);
if (rows.some((r) => !r.agrees)) process.exitCode = 1;
